### ISSUE TITLE
YAML: Rearrange component keys related to electrolyte purity

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#115]
In the YAML file, the entries the `purity` and `supplier` keys in `electrochemical_system.electrolyte.components` should be adapted once the structure is more clear. Even though most of these aspects are not so relevant for echemdb since the values are often not provided in the literature it is important to set a certain standard for newly acquired data.

# Examples:
## acid
```yaml
name: HClO4
supplier: Merck
brand: suprapure
type: acid
purity:
    refinement: 
        description: Done this an that
        supplied grade: # only required 
             unit: 99.99
             value: pct
    grade: # The supplier purity unless refinement is given
        unit: 99.9999
        value: pct

```

## solvent
```yaml
name: H2O
type: solvent
purity:
    refinement: 
        dscription: Refined with MilliPore
        feed purity:
             TOC:
             conductivity: 
    TOC: ...
    conductivity: ....
```

## gas
```yaml
name: N2
type: gas
purity:
    TODO
```
