### ISSUE TITLE
Website Stlye

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#117]
Change the style of the website.

- [ ] Elucidate which pages should be shown.
- [ ] Define a useful table to represent the entries currently in the repository.

**Comment by DunklesArchipel** [comment]
To expand the TOC add
```yaml
theme:
  features:
     - navigation.expand
```

the TOC is generated in the NAVIAGTION.md in the root directory.
