### ISSUE TITLE
Phrasing of preparation a bit unfortunate

### ISSUE THREAD

**Issue by saraedum** [echemdb/website#156]
e.g., on one page it says

> The Pt(544) electrode was prepared by:
Prior to each experiment the electrodes were flame annealed, cooled in a hydrogen/argon atmosphere and transferred to the cell protected by a drop of ultra-pure water saturated with these gases.

maybe we can write the intro in a more neutral way so that more types of sentences make sense afterwards.

**Comment by DunklesArchipel** [comment]
I guess it would be sufficient to write.

`Preparation procedure`

or 

`Preparation notes`

**Comment by DunklesArchipel** [comment]
Maybe we should also change the preparation procedure into a list, where each item describes a step in the procedure

**Comment by DunklesArchipel** [comment]
suggested metadata structure
```yaml
preparation:
    type: UHV #ambient conditions, UHV, etc
    steps:
    - Sputtering with Argon.
    - Annealing at 1500 K
    - Cooling in an O2 atmosphere
```
