### ISSUE TITLE
Create 'entry.unit_value' from units and values in the yaml file

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#70]
```yaml
scan rate:
   unit: V / s
   value: 50
```

An object that prints "50 V/s" when `entry.scan_rate` is called, while unit and value are still accessible via `entry.scan_rate.value`
